language: node_js
node_js:
- 0.10
before_install:
- sudo apt-get update -qq
- sudo apt-get install ant
before_script:
- ant resolve
- npm install
- bower install
- gulp
script:
- ant dist
deploy:
  provider: releases
  api_key:
    secure: NBrHvzEAdURXYDgRMrd90IzIA+2I6AFUHN+Zs6Lm6clCaAoEQaTKeBc2jhWAClQIQMrHaJMuo/RtWsQRvCcxuXy78OIKjz3AoUx53TrqeG5mU9v+KG+jJlYso7+NS3qv1LZePKadwtH+lvEsWqZ9WDc/HiNwc4ihoN/3AMFk0s0=
  file: dist/decks.zip
  on:
    repo: gundisalwa/decks
    all_branches: true
    tags: true